name: Deploy on main push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testing
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "[$(date)] Deploying via GitHub Actions..." >> /opt/webtools/github_actions_deploy.log
            sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /opt/webtools
            cd /opt/webtools
            git pull origin main
            make deploy
            echo "[$(date)] Done!" >> /opt/webtools/github_actions_deploy.log
